import '../check_rates_showing_bottomsheet/widgets/servicelist_item_widget.dart';import 'package:flutter/material.dart';import 'package:the_s_application5/core/app_export.dart';class CheckRatesShowingBottomsheet extends StatelessWidget {const CheckRatesShowingBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SingleChildScrollView(child: Expanded(child: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 10, right: 24, bottom: 10), decoration: AppDecoration.fill1, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(width: getHorizontalSize(60), child: Divider(height: getVerticalSize(6), thickness: getVerticalSize(6), color: appTheme.gray300)), Padding(padding: getPadding(top: 28), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(width: getHorizontalSize(83), child: Text("1254 Kanata,\nOttawa", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleSmall)), Padding(padding: getPadding(top: 8), child: Text("Picked Up", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.labelLarge))]), Spacer(flex: 56), CustomImageView(svgPath: ImageConstant.imgArrowright, height: getSize(24), width: getSize(24), margin: getMargin(top: 20, bottom: 17)), Spacer(flex: 43), Padding(padding: getPadding(bottom: 1), child: Column(crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(width: getHorizontalSize(93), child: Text("2541  Orleans,\nToronto", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: theme.textTheme.titleSmall)), Padding(padding: getPadding(top: 7), child: Text("Destionation", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.labelLarge))]))])), Padding(padding: getPadding(top: 16), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.gray10001)), Expanded(child: Padding(padding: getPadding(top: 13, bottom: 39), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(15));}, itemCount: 3, itemBuilder: (context, index) {return ServicelistItemWidget(onTapImgClose: () {onTapImgClose(context);});})))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapImgClose(BuildContext context) { Navigator.pop(context); } 
 }
