import 'package:flutter/material.dart';import 'package:the_s_application5/core/app_export.dart';import 'package:the_s_application5/widgets/custom_elevated_button.dart';class ScanBarcodeOneBottomsheet extends StatelessWidget {const ScanBarcodeOneBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SingleChildScrollView(child: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 10, right: 24, bottom: 10), decoration: AppDecoration.gradientnamewhiteA700opacity0namewhiteA7001, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(width: getHorizontalSize(60), child: Divider(height: getVerticalSize(6), thickness: getVerticalSize(6), color: appTheme.gray300)), Spacer(), Text("Scan Successfully", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleLarge), Container(width: getHorizontalSize(298), margin: getMargin(left: 13, top: 10, right: 14), child: Text("Yey! Your package has been identified, to make sure this is your item. Please see the details. ", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium)), Padding(padding: getPadding(top: 15), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.gray10001)), Container(margin: getMargin(top: 13), padding: getPadding(all: 10), decoration: AppDecoration.outline1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.gray100, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder10), child: Container(height: getSize(50), width: getSize(50), padding: getPadding(all: 13), decoration: AppDecoration.fill9.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Stack(alignment: Alignment.center, children: [CustomImageView(svgPath: ImageConstant.imgClose, height: getVerticalSize(20), width: getHorizontalSize(19), alignment: Alignment.bottomLeft, onTap: () {onTapImgClose(context);}), CustomImageView(svgPath: ImageConstant.imgArrowdown, height: getSize(24), width: getSize(24), alignment: Alignment.center)]))), Padding(padding: getPadding(left: 14, top: 2, bottom: 4), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("MA84561259", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleSmall), Padding(padding: getPadding(top: 3), child: Text("Processed at sort facility", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.bodyMedium))])), Spacer(), Padding(padding: getPadding(top: 16, right: 4, bottom: 16), child: Text("2 Hrs", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.labelLarge))])), CustomElevatedButton(text: "View Detail", margin: getMargin(top: 40, bottom: 39), buttonStyle: CustomButtonStyles.fillPrimary.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(56)))), buttonTextStyle: CustomTextStyles.titleMediumWhiteA70001_1)]))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapImgClose(BuildContext context) { Navigator.pop(context); } 
 }
