import 'package:flutter/material.dart';import 'package:the_s_application5/core/app_export.dart';import 'package:the_s_application5/widgets/app_bar/appbar_image.dart';import 'package:the_s_application5/widgets/app_bar/appbar_subtitle.dart';import 'package:the_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:the_s_application5/widgets/custom_icon_button.dart';class ScanBarcodeScreen extends StatelessWidget {const ScanBarcodeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA70001, appBar: CustomAppBar(height: getVerticalSize(73), leadingWidth: 58, leading: AppbarImage(height: getSize(22), width: getSize(22), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 36, top: 27, bottom: 24), onTap: () {onTapArrowleft8(context);}), centerTitle: true, title: AppbarSubtitle(text: "Scan Barcode"), actions: [AppbarImage(height: getSize(22), width: getSize(22), svgPath: ImageConstant.imgOverflowmenuOnprimary, margin: getMargin(left: 36, top: 27, right: 36, bottom: 24))], styleType: Style.bgShadow), body: SizedBox(height: getVerticalSize(695), width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle135, height: getVerticalSize(697), width: getHorizontalSize(375), alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: getVerticalSize(695), width: double.maxFinite, decoration: AppDecoration.fill10, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(padding: getPadding(left: 77, top: 28, right: 77, bottom: 28), decoration: AppDecoration.fill1, child: Padding(padding: getPadding(bottom: 24), child: Text("Hold camera to scan barcode", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleMedium)))), CustomIconButton(height: 38, width: 38, margin: getMargin(bottom: 84), padding: getPadding(all: 6), decoration: IconButtonStyleHelper.fillWhiteA70001, alignment: Alignment.bottomCenter, child: CustomImageView(svgPath: ImageConstant.imgWarning))])))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft8(BuildContext context) { Navigator.pop(context); } 
 }
